name: Vite React Crowdfunding CI/CD with Ansible & Firebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

    - name: Run tests (if present)
      run: npm run test --if-present

    - name: Build Vite project
      run: npm run build

    # ---- Ansible Section (Post-build automation) ----
    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Run Ansible Playbook
      run: ansible-playbook deploy/deploy.yml
      # env:
      #   SOME_SECRET: ${{ secrets.SOME_SECRET }}

    # ---- SonarCloud Analysis ----
    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v2
      with:
        args: >
          -Dsonar.projectKey=Pavanmk1310_Devops
          -Dsonar.organization=pavanmk1310
          -Dsonar.sources=src

    - name: Wait for SonarCloud Quality Gate Result
      uses: sonarsource/sonarqube-quality-gate-action@v1.1.0

    # ---- Firebase Deployment ----
    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@v13.0.1
      with:
        args: deploy --only hosting
        # You can specify a specific project or site here if needed
